### ISSUE TITLE
os.path.isfile(unix socket) always returns False

### ISSUE THREAD

**Issue by RIscRIpt** [ateska/ramona#39]
https://github.com/ateska/ramona/blob/master/ramona/socketuri.py#L128

    assert not os.path.isfile(fname)

`os.path.isfile` always returns False on a unix socket file _(at least in my system)_:

    >>> sys.version
    '2.7.3 (default, Mar 13 2014, 11:03:55) \n[GCC 4.7.2]'
    >>> os.path.exists("unix.sock")
    True
    >>> os.path.isfile("unix.sock")
    False
    >>>

I think, you should consider changing this assertion, as it always succeed.

**Comment by ateska** [comment]
Hi,
Very good observation.
I'll change that assertion.
Thanks,
Ales
